#source 'https://github.com/gmunhoz/CollieGallery.git'

project 'CollieGallery'
inhibit_all_warnings!
use_frameworks!
platform :ios, '10.0'

target 'CollieGallery_Example' do
    pod 'CollieGallery', :path => '../'
end

target 'CollieGallery_Tests' do
    pod 'CollieGallery', :path => '../'
end

